server:
  port: 8082
  servlet:
    session.timeout: 60000
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3310/yc125res?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations:
        -classpath*: schema-all.sql
      data-locations:
        -classpath*: data-all.sql
      username: root
      password: 123456
      mode: AlWAYS



